# Generated by Django 6.0.3 on 2026-03-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('brokerages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coverage_types', to='brokerages.brokerage', verbose_name='Corretora')),
                ('insurance_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coverage_types', to='branches.insurancebranch', verbose_name='Ramo de Seguro')),
            ],
            options={
                'verbose_name': 'Tipo de Cobertura',
                'verbose_name_plural': 'Tipos de Cobertura',
                'ordering': ['name'],
            },
        ),
    ]
