# Generated by Django 6.0.3 on 2026-03-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cnpj', models.CharField(blank=True, default='', max_length=18, verbose_name='CNPJ')),
                ('susep_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SUSEP')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('contact_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome do Contato')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurers', to='brokerages.brokerage', verbose_name='Corretora')),
            ],
            options={
                'verbose_name': 'Seguradora',
                'verbose_name_plural': 'Seguradoras',
                'ordering': ['name'],
            },
        ),
    ]
