# Generated by Django 6.0.3 on 2026-03-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('individual', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], max_length=20, verbose_name='Tipo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ')),
                ('susep_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SUSEP')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='CEP')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão (%)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='brokerages.brokerage', verbose_name='Corretora')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('susep_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SUSEP')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão (%)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='agents.agent', verbose_name='Agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producers', to='brokerages.brokerage', verbose_name='Corretora')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Produtor',
                'verbose_name_plural': 'Produtores',
                'ordering': ['name'],
            },
        ),
    ]
