# Generated by Django 6.0.3 on 2026-03-16 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('price_per_user', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor por Usuário/Mês')),
                ('max_users', models.IntegerField(blank=True, help_text='Vazio = ilimitado', null=True, verbose_name='Máx. Usuários')),
                ('features', models.JSONField(blank=True, null=True, verbose_name='Funcionalidades')),
                ('is_free', models.BooleanField(default=False, verbose_name='Plano Gratuito')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
                'ordering': ['price_per_user'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('cancelled', 'Cancelado'), ('suspended', 'Suspenso')], default='active', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(verbose_name='Início')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiração')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='brokerages.brokerage', verbose_name='Corretora')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='plans.plan', verbose_name='Plano')),
            ],
            options={
                'verbose_name': 'Assinatura',
                'verbose_name_plural': 'Assinaturas',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('payment_date', models.DateTimeField(verbose_name='Data do Pagamento')),
                ('status', models.CharField(choices=[('paid', 'Pago'), ('pending', 'Pendente'), ('failed', 'Falhou'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='Status')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='plans.subscription', verbose_name='Assinatura')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-payment_date'],
            },
        ),
    ]
