# Generated by Django 6.0.3 on 2026-03-16 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('legal_name', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('trade_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nome Fantasia')),
                ('susep_code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código SUSEP')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='CEP')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brokerages/logos/', verbose_name='Logo')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo'), ('pending_payment', 'Pagamento Pendente'), ('overdue', 'Pagamento em Atraso')], default='active', max_length=20, verbose_name='Status')),
                ('default_commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Comissão Padrão (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Corretora',
                'verbose_name_plural': 'Corretoras',
                'ordering': ['legal_name'],
            },
        ),
    ]
