# Generated by Django 6.0.3 on 2026-03-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('brokerages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(choices=[('individual', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='individual', max_length=20, verbose_name='Tipo')),
                ('name', models.CharField(max_length=255, verbose_name='Nome / Razão Social')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF / CNPJ')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone')),
                ('secondary_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefone Secundário')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, default='', max_length=2, verbose_name='Estado')),
                ('zip_code', models.CharField(blank=True, default='', max_length=10, verbose_name='CEP')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Observações')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('assigned_producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='agents.producer', verbose_name='Produtor Responsável')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='brokerages.brokerage', verbose_name='Corretora')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
