# Generated by Django 6.0.3 on 2026-03-16 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('brokerages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrokerage',
            name='brokerage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brokerages', to='brokerages.brokerage', verbose_name='Corretora'),
        ),
        migrations.AddField(
            model_name='userbrokerage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_brokerages', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='userbrokerage',
            unique_together={('user', 'brokerage')},
        ),
    ]
