# Generated by Django 6.0.3 on 2026-03-16 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brokerages', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('code', models.CharField(blank=True, default='', max_length=20, verbose_name='Código')),
                ('description', models.TextField(blank=True, default='', verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_branches', to='brokerages.brokerage', verbose_name='Corretora')),
            ],
            options={
                'verbose_name': 'Ramo de Seguro',
                'verbose_name_plural': 'Ramos de Seguro',
                'ordering': ['name'],
                'unique_together': {('brokerage', 'name')},
            },
        ),
    ]
